# YLS-Android 문서 사이트를 배포하는 workflow입니다.
name: Deploy docs

on:
    push:
        branches: [ master ]

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            -   name: set up JDK 17
                uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: gradle

            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew

            -   name: Build dokka site
                run: ./gradlew dokkaHtml

            -   name: Deploy docs site to website
                uses: JamesIves/github-pages-deploy-action@releases/v3
                with:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    BRANCH: gh-page
                    FOLDER: yls/build/dokka/html/
                    TARGET_FOLDER: 'docs/0.x/'
